Я буду писать заметки-конспект в произвольном формате.
Кратко и только с упоминанием вещей, которые я сочту значимыми.

* Почему доказывать в Lean может быть легче, чем "на бумаге"?

** Визуальное представление пруфстейта

Если ты новичок в написании математических доказательств, то можешь удивиться,
насколько сложно отличить гипотезы от целей на бумаге после нескольких шагов
чередования прямого и обратного рассуждения, или насколько легко потерять один
из вариантов при их разделении (например, при рассмотрении \land, \iff).

Визуальное представление пруфстейта (состояния доказательства) в режиме
реального времени в Lean освобождает от необходимости держать его в рабочей
памяти (в голове). Особенно, у вас не IQ > 200 и временная память весьма
ограничена.

** Обратная связь

Она мгновенная, можно постепенно продвигаться в конструировании доказательства,
пока не получишь работающее. Lean гарантирует его полную корректность: без
путаницы знаков при подстановках в неравенствах, без делений на ноль, без
пропущенных членов в алгебре. Короче, элиминирует ошибки приматов.

** Тактики

Это такие формальные атомарные шаги в рассуждении, которые по сути делают
объективным то, что в доказательстве, состоящем только из прозы, может быть
субъективным. Более того, они потталкивают к определённым стилям построения
математических аргументов, которые общеприняты в стандартной математической
прозе, но которые люди часто не усваивают с трудом.

Кстати, в этой книге есть кастомные тактики, придуманные специально как аналоги
шагов доказательства "на бумаге".

* О книге

Эта книга чуть более плавная (лёгкая), нежели Mathematics in Lean, которая
предполагает больший математический опыт: написание идиоматичного
доказательства, даже для элементарных утверждений, требует определенной
математической зрелости. Так получилось благодаря аккуратному выбору упражнений
и тому, что автор использует некий ограниченный "диалект" Lean, которого впрочем
достаточно для нужд этой книги.

Короче, знания школьной алгебры должно быть достаточно, чтобы проходить эту
книгу. Анализа в ней не будет.
